### ISSUE TITLE
Page break issue

### ISSUE THREAD

**Issue by samawiamoin** [iron-software/iron-pdf-example-hello-world-csharp#1]
I am applying page break styles to table but these are not applying in creating pdf.

**Comment by TronActive** [comment]
I am having the same exact issue in my project. I need to get this working ASAP.

**Comment by ww-sits** [comment]
Same here, the page break avoid div does not work as well.

**Comment by mbkrispy** [comment]
For the fix, update to the latest version of IronPDF and follow the following guide on Page Breaks:
https://ironpdf.com/how-to/html-to-pdf-page-breaks/
