### ISSUE TITLE
Unity-Version 2018.3.14f crashes when using the net40 version of iron pdf

### ISSUE THREAD

**Issue by SmartMonkey-git** [iron-software/iron-pdf-example-hello-world-csharp#3]
Hello IronPDF-Crew,

I want to use the IronPDF Plugin in Unity, specifically in a UWP build, but using the following code Unity just crashes.

            HtmlToPdf Renderer = new IronPdf.HtmlToPdf();
            PdfDocument PDF = Renderer.RenderHtmlAsPdf("<h1>Hello IronPdf</h1>");
            string OutputPath = "HtmlToPDF.pdf";
            PDF.SaveAs(Path.Combine(Application.persistentDataPath, OutputPath));

Is there a known solution on this?

**Comment by mbkrispy** [comment]
This will work now with the latest version with replacing the first line with

`var Renderer = new ChromePdfRenderer();`
