### ISSUE TITLE
After upgrade to V 2020.8.1 and 9.0 the deployment (Azure web app) will taking more than 25 min

### ISSUE THREAD

**Issue by NST77** [iron-software/iron-pdf-example-hello-world-csharp#4]
After upgrade IronPDF version 2020.8.1 or 2020.9.0, the Azure web app ( ASP.NET MVC 5) deployment takes more than 25 minutes and sometimes failed.

For confirming this, we downgraded the IronPDF version to 2020.6.0 and deployed the same to the Azure web app and it will only be taken 1 min and 45 sec. 

After publishing the web app with IronPDF version 2020.8.1 or 2020.9.0, the Azure portal showing extremely high CPU usage (100%) within the Azure App Service.

After downgrade to 2020.6.0, The CPU usage has stabilized at around 10-30% in Azure App Service.

![2020-09-15_20-26-26](https://user-images.githubusercontent.com/14166321/93230528-62eb5880-f795-11ea-8837-60cba389a629.jpg)

![2020-09-15_20-29-44](https://user-images.githubusercontent.com/14166321/93230588-74ccfb80-f795-11ea-9957-c5ee7ba0cb91.jpg)

Please advice.

**Comment by mbkrispy** [comment]
Long  deployment issues have been solved in the latest most version of IronPDF. Please upgrade.

Further Guide : https://ironpdf.com/how-to/azure/
